# Generated by Django 4.2.2 on 2023-06-19 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 18, 19, 32, 997139)),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
