# Generated by Django 4.2.2 on 2023-06-13 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authcodes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthCodes',
            new_name='AuthCode',
        ),
    ]
