# Generated by Django 4.2.2 on 2023-06-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_authcodes_authcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='date',
            new_name='created_at',
        ),
    ]
