# Generated by Django 4.2.2 on 2023-06-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_authcode_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='authcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='authcode',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 14, 11, 30, 36, 83093)),
        ),
    ]
